In [8]:
import pandas as pd
import numpy as np
pd.set_option('html', True)
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 25)

In [9]:
dfPassport = pd.read_csv("../data/passport-index.csv")
dfPassport

,Country,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,...,Uruguay,Uzbekistan,Vanuatu,Vatican City,Venezuela,Viet Nam,Yemen,Zambia,Zimbabwe,Unnamed: 200
0,Afghanistan,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1,Albania,0,1,0,1,0,1,0,1,0,...,0,0,0,1,0,0,0,1,0,NaN
2,Algeria,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,NaN
3,Andorra,0,1,0,1,0,1,1,1,1,...,1,0,1,1,1,0,0,1,1,NaN
4,Angola,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,1,NaN
5,Antigua and Barbuda,0,1,0,1,0,1,0,1,0,...,0,0,1,1,1,0,0,1,1,NaN
6,Argentina,0,1,0,1,0,1,1,1,0,...,1,0,1,1,1,0,0,1,1,NaN
7,Armenia,0,1,0,0,0,1,1,1,0,...,1,1,0,0,0,0,0,0,0,NaN
8,Australia,0,1,0,1,0,1,1,1,1,...,1,0,1,1,1,0,0,1,1,NaN
9,Austria,0,1,0,1,0,1,1,1,1,...,1,0,1,1,1,0,0,1,1,NaN
10,Azerbaijan,0,1,0,0,0,1,0,1,0,...,0,1,1,0,0,0,0,0,1,NaN
11,Bahamas,0,1,0,1,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,United Arab Emirates,0,1,0,1,0,1,1,1,0,...,0,0,1,1,0,0,1,1,1,NaN
188,United Kingdom,0,1,0,1,0,1,1,1,1,...,1,0,1,1,1,1,0,1,1,NaN
189,United States of America,0,1,0,1,0,1,1,1,1,...,1,0,1,1,0,0,0,1,1,NaN
190,Uruguay,0,1,0,1,0,0,1,1,0,...,1,0,1,1,1,0,0,1,1,NaN
191,Uzbekistan,0,0,0,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,1,NaN
192,Vanuatu,0,0,0,1,0,1,0,1,0,...,0,0,1,1,0,0,0,1,1,NaN
193,Vatican City,0,1,0,1,0,1,1,1,1,...,0,0,1,1,0,0,0,1,1,NaN
194,Venezuela,0,1,0,1,0,1,1,1,0,...,1,0,0,1,1,0,0,1,0,NaN
195,Viet Nam,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,NaN
196,Yemen,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,NaN
197,Zambia,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,1,1,NaN
198,Zimbabwe,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,1,NaN

In [11]:
dfAsylumSeekers = pd.read_csv("../data/ref_by_c_asylum/ref_by_c_asylum.csv")
dfAsylumSeekers

CParserError: Error tokenizing data. C error: Expected 3 fields in line 5, saw 62