## Refugees by Country or Territory of Asylum Data Set

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

In [3]:
import plotly 
import plotly.plotly as py 
import plotly.figure_factory as ff
from plotly.graph_objs import *
import cufflinks as cf
plotly.tools.set_credentials_file(username='bluecrayon52', api_key='jidjcpp2L31WYmRfaHZx')

### Data Cleaning:

In [14]:
df = pd.read_csv("../data/ref_by_c_asylum/ref_by_c_asylum.csv", header = 2)                 

# re-naming a column 
#df=df.rename(columns = {'Country Name':'country'})
df.set_index('Country Name')

# # deleting various columns 
del df["Indicator Name"]
del df["Indicator Code"]

# # dropping empty rows 
df=df.dropna(subset=['1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002',
                  '2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016'], 
                   how='all')

# dropping empty columns 
df=df.dropna(axis=1, how='all')
df.head(20)

,Country Name,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN
1,Afghanistan,AFG,50.0,38.0,60025.0,32132.0,19131.0,19605.0,18775.0,5.0,...,42.0,37.0,37.0,6434.0,3009.0,16187.0,16863.0,300423.0,257554.0,59770.0
2,Angola,AGO,11557.0,11022.0,11002.0,10878.0,10686.0,10884.0,9381.0,9364.0,...,12069.0,12710.0,14734.0,15155.0,16223.0,23413.0,23783.0,15474.0,15555.0,15537.0
3,Albania,ALB,NaN,NaN,3000.0,3000.0,3000.0,4720.0,4925.0,30.0,...,77.0,65.0,70.0,76.0,82.0,86.0,93.0,104.0,104.0,111.0
5,Arab World,ARB,4235545.0,3811595.0,4000509.0,4189545.0,4352945.0,4337009.0,4159630.0,4243164.0,...,7513460.0,7206343.0,6955072.0,7077529.0,6657656.0,6638911.0,7794808.0,8375066.0,8304742.0,8439935.0
6,United Arab Emirates,ARE,NaN,NaN,NaN,433.0,381.0,407.0,464.0,519.0,...,159.0,209.0,279.0,538.0,677.0,631.0,603.0,417.0,663.0,888.0
7,Argentina,ARG,11735.0,11529.0,11515.0,11636.0,11901.0,10314.0,10430.0,10522.0,...,3263.0,2845.0,3230.0,3276.0,3361.0,3488.0,3362.0,3498.0,3207.0,3222.0
8,Armenia,ARM,NaN,NaN,300000.0,334000.0,304039.0,218950.0,218950.0,219000.0,...,4566.0,3953.0,3607.0,3296.0,2918.0,2854.0,13732.0,17640.0,19319.0,17873.0
10,Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN
11,Australia,AUS,97915.0,53117.0,52604.0,53505.0,57575.0,62145.0,67313.0,66074.0,...,22164.0,20919.0,22548.0,21805.0,23434.0,30083.0,34503.0,35582.0,36917.0,42107.0
12,Austria,AUT,34938.0,34508.0,62355.0,57687.0,40703.0,34385.0,89116.0,84394.0,...,30773.0,37557.0,38906.0,42630.0,47073.0,51730.0,55598.0,60747.0,72216.0,93182.0
13,Azerbaijan,AZE,NaN,NaN,246000.0,228840.0,231635.0,233682.0,233692.0,233715.0,...,2352.0,2061.0,1642.0,1891.0,1730.0,1468.0,1380.0,1299.0,1278.0,1183.0
14,Burundi,BDI,268403.0,270136.0,271745.0,271883.0,300302.0,173017.0,20733.0,22028.0,...,24483.0,21093.0,24967.0,29365.0,35659.0,41813.0,45490.0,52936.0,53363.0,57462.0
15,Belgium,BEL,25911.0,24071.0,24292.0,24908.0,19497.0,31691.0,36060.0,36060.0,...,17575.0,17026.0,15545.0,17892.0,22402.0,22024.0,25629.0,29179.0,35314.0,42128.0
16,Benin,BEN,456.0,456.0,293.0,156241.0,70406.0,23843.0,5960.0,2918.0,...,7621.0,6933.0,7205.0,7139.0,7217.0,4966.0,194.0,415.0,530.0,799.0
17,Burkina Faso,BFA,350.0,320.0,5670.0,6604.0,49990.0,29777.0,28381.0,1801.0,...,535.0,557.0,543.0,531.0,546.0,39306.0,29234.0,31894.0,34017.0,32546.0
18,Bangladesh,BGD,145.0,40260.0,245154.0,198954.0,116228.0,51118.0,30692.0,21603.0,...,27573.0,28389.0,228586.0,229253.0,229669.0,230697.0,231145.0,232472.0,231958.0,276198.0
19,Bulgaria,BGR,NaN,NaN,218.0,450.0,1060.0,1320.0,1430.0,390.0,...,4836.0,5129.0,5393.0,5530.0,5688.0,2288.0,4320.0,11046.0,16557.0,17774.0
20,Bahrain,BHR,1780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,48.0,139.0,165.0,199.0,289.0,294.0,311.0,247.0,270.0
21,"Bahamas, The",BHS,NaN,NaN,374.0,59.0,NaN,8.0,48.0,60.0,...,NaN,NaN,NaN,28.0,28.0,37.0,15.0,13.0,8.0,9.0

### ISO APHLA-3 Country codes

In [16]:
# read in the codes
iso_3 = pd.read_excel("../data/ref_by_c_asylum/country_code_web.xls",  header=1)
# rename column for merging 
iso_3=iso_3.rename(columns = {'ISO ALPHA-3 code':'Country Code'})
# get rid of redundant data
iso_3=iso_3.drop('Country or area name', axis=1)
iso_3.head(20)
# merge to filter codes
df = pd.merge(iso_3, df)
# save the dataframe 
#df.to_pickle("../data/ref_by_c_asylum/refugee_asy_pickle")
refugees = pd.read_pickle("../data/ref_by_c_asylum/refugee_asy_pickle")
refugees.head(20)

,Country Code,Country Name,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,AFG,Afghanistan,50.0,38.0,60025.0,32132.0,19131.0,19605.0,18775.0,5.0,...,42.0,37.0,37.0,6434.0,3009.0,16187.0,16863.0,300423.0,257554.0,59770.0
1,ALB,Albania,NaN,NaN,3000.0,3000.0,3000.0,4720.0,4925.0,30.0,...,77.0,65.0,70.0,76.0,82.0,86.0,93.0,104.0,104.0,111.0
2,DZA,Algeria,169110.0,169124.0,219314.0,219067.0,219073.0,192489.0,190267.0,170746.0,...,94137.0,94093.0,94137.0,94144.0,94148.0,94133.0,94150.0,94128.0,94182.0,94220.0
3,AGO,Angola,11557.0,11022.0,11002.0,10878.0,10686.0,10884.0,9381.0,9364.0,...,12069.0,12710.0,14734.0,15155.0,16223.0,23413.0,23783.0,15474.0,15555.0,15537.0
4,ATG,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN
5,ARG,Argentina,11735.0,11529.0,11515.0,11636.0,11901.0,10314.0,10430.0,10522.0,...,3263.0,2845.0,3230.0,3276.0,3361.0,3488.0,3362.0,3498.0,3207.0,3222.0
6,ARM,Armenia,NaN,NaN,300000.0,334000.0,304039.0,218950.0,218950.0,219000.0,...,4566.0,3953.0,3607.0,3296.0,2918.0,2854.0,13732.0,17640.0,19319.0,17873.0
7,ABW,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN
8,AUS,Australia,97915.0,53117.0,52604.0,53505.0,57575.0,62145.0,67313.0,66074.0,...,22164.0,20919.0,22548.0,21805.0,23434.0,30083.0,34503.0,35582.0,36917.0,42107.0
9,AUT,Austria,34938.0,34508.0,62355.0,57687.0,40703.0,34385.0,89116.0,84394.0,...,30773.0,37557.0,38906.0,42630.0,47073.0,51730.0,55598.0,60747.0,72216.0,93182.0
10,AZE,Azerbaijan,NaN,NaN,246000.0,228840.0,231635.0,233682.0,233692.0,233715.0,...,2352.0,2061.0,1642.0,1891.0,1730.0,1468.0,1380.0,1299.0,1278.0,1183.0
11,BHS,"Bahamas, The",NaN,NaN,374.0,59.0,NaN,8.0,48.0,60.0,...,NaN,NaN,NaN,28.0,28.0,37.0,15.0,13.0,8.0,9.0
12,BHR,Bahrain,1780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,48.0,139.0,165.0,199.0,289.0,294.0,311.0,247.0,270.0
13,BGD,Bangladesh,145.0,40260.0,245154.0,198954.0,116228.0,51118.0,30692.0,21603.0,...,27573.0,28389.0,228586.0,229253.0,229669.0,230697.0,231145.0,232472.0,231958.0,276198.0
14,BRB,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
15,BLR,Belarus,NaN,NaN,NaN,NaN,1822.0,28988.0,30525.0,50.0,...,649.0,609.0,580.0,589.0,595.0,576.0,604.0,925.0,1809.0,1632.0
16,BEL,Belgium,25911.0,24071.0,24292.0,24908.0,19497.0,31691.0,36060.0,36060.0,...,17575.0,17026.0,15545.0,17892.0,22402.0,22024.0,25629.0,29179.0,35314.0,42128.0
17,BLZ,Belize,30657.0,29969.0,20351.0,8912.0,8857.0,8750.0,8534.0,8387.0,...,358.0,277.0,230.0,134.0,78.0,28.0,21.0,10.0,35.0,NaN
18,BEN,Benin,456.0,456.0,293.0,156241.0,70406.0,23843.0,5960.0,2918.0,...,7621.0,6933.0,7205.0,7139.0,7217.0,4966.0,194.0,415.0,530.0,799.0
19,BOL,Bolivia,200.0,341.0,491.0,669.0,734.0,681.0,698.0,333.0,...,632.0,664.0,679.0,695.0,716.0,733.0,748.0,763.0,775.0,761.0
20,BIH,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40000.0,...,7367.0,7257.0,7132.0,7016.0,6933.0,6903.0,6926.0,6890.0,6798.0,5256.0
21,BWA,Botswana,1179.0,1054.0,497.0,514.0,503.0,266.0,214.0,281.0,...,2465.0,3019.0,3022.0,2986.0,3312.0,2785.0,2773.0,2645.0,2130.0,2080.0
22,BRA,Brazil,5335.0,5389.0,5439.0,6198.0,2223.0,2050.0,2212.0,2260.0,...,20783.0,3852.0,4232.0,4357.0,4477.0,4689.0,5196.0,7490.0,8707.0,9634.0
23,VGB,British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN
24,BGR,Bulgaria,NaN,NaN,218.0,450.0,1060.0,1320.0,1430.0,390.0,...,4836.0,5129.0,5393.0,5530.0,5688.0,2288.0,4320.0,11046.0,16557.0,17774.0
25,BFA,Burkina Faso,350.0,320.0,5670.0,6604.0,49990.0,29777.0,28381.0,1801.0,...,535.0,557.0,543.0,531.0,546.0,39306.0,29234.0,31894.0,34017.0,32546.0
26,BDI,Burundi,268403.0,270136.0,271745.0,271883.0,300302.0,173017.0,20733.0,22028.0,...,24483.0,21093.0,24967.0,29365.0,35659.0,41813.0,45490.0,52936.0,53363.0,57462.0
27,KHM,Cambodia,NaN,NaN,NaN,5.0,10.0,15.0,16.0,14.0,...,179.0,164.0,135.0,129.0,64.0,77.0,68.0,63.0,76.0,61.0
28,CMR,Cameroon,49876.0,45237.0,42233.0,44013.0,44036.0,45781.0,46407.0,47057.0,...,60137.0,81037.0,99957.0,104275.0,100373.0,98969.0,114753.0,264126.0,342973.0,375393.0
29,CAN,Canada,154761.0,170916.0,183723.0,183241.0,186563.0,152125.0,138435.0,125184.0,...,175741.0,173651.0,169434.0,165549.0,164883.0,163756.0,160349.0,149163.0,135888.0,97311.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,SUR,Suriname,NaN,NaN,52.0,50.0,39.0,NaN,NaN,11.0,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN
154,SWZ,Swaziland,42074.0,49569.0,55580.0,48889.0,643.0,712.0,575.0,592.0,...,789.0,775.0,759.0,759.0,759.0,505.0,507.0,515.0,696.0,705.0
155,SWE,Sweden,109663.0,124470.0,131073.0,162402.0,200791.0,199212.0,191171.0,186725.0,...,75078.0,77038.0,81356.0,82629.0,86615.0,92872.0,114175.0,142207.0,169520.0,230103.0
156,CHE,Switzerland,40943.0,45622.0,51930.0,56586.0,75295.0,82943.0,84413.0,83203.0,...,45653.0,46132.0,46203.0,48813.0,50416.0,50747.0,52464.0,62620.0,73336.0,82608.0
157,SYR,Syrian Arab Republic,284856.0,296256.0,309672.0,353392.0,366283.0,373530.0,375150.0,383906.0,...,1955236.0,1567595.0,1526575.0,1501442.0,1242391.0,975695.0,666547.0,677756.0,581113.0,562811.0
158,TJK,Tajikistan,NaN,NaN,3000.0,300.0,695.0,620.0,1166.0,2174.0,...,1133.0,1799.0,2679.0,3131.0,3323.0,2248.0,2048.0,2026.0,1969.0,2719.0
159,THA,Thailand,99821.0,88164.0,63625.0,119232.0,100817.0,106565.0,107962.0,169154.0,...,125643.0,112932.0,105297.0,96675.0,89253.0,84479.0,136499.0,130238.0,108261.0,106426.0
160,MKD,"Macedonia, FYR",NaN,NaN,32000.0,31452.0,14891.0,9048.0,5089.0,3500.0,...,1235.0,1672.0,1542.0,1398.0,1130.0,1077.0,982.0,883.0,701.0,629.0
161,TLS,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
162,TGO,Togo,3477.0,3406.0,3353.0,3280.0,12370.0,10876.0,12589.0,12682.0,...,1328.0,9377.0,8531.0,14051.0,19270.0,23540.0,20613.0,21778.0,21953.0,12476.0
163,TON,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,3.0,3.0,NaN,NaN,NaN
164,TTO,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.0,33.0,37.0,29.0,22.0,18.0,20.0,83.0,113.0,89.0
165,TUN,Tunisia,30.0,130.0,111.0,99.0,19.0,199.0,176.0,506.0,...,101.0,94.0,92.0,89.0,4097.0,1435.0,730.0,901.0,665.0,636.0
166,TUR,Turkey,28000.0,30462.0,28477.0,23267.0,24927.0,12841.0,8166.0,2446.0,...,6956.0,11103.0,10350.0,10032.0,14465.0,267063.0,609938.0,1587374.0,2541352.0,2869379.0
167,TKM,Turkmenistan,NaN,NaN,NaN,15400.0,15400.0,23323.0,15580.0,15787.0,...,125.0,79.0,60.0,62.0,59.0,46.0,45.0,35.0,26.0,26.0
168,TCA,Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,NaN
169,UGA,Uganda,145718.0,162521.0,196290.0,286500.0,286500.0,229350.0,264294.0,188513.0,...,228959.0,162132.0,127345.0,135801.0,139448.0,197877.0,220555.0,385513.0,477187.0,940815.0
170,UKR,Ukraine,NaN,NaN,NaN,NaN,5193.0,5193.0,3591.0,4564.0,...,7277.0,7201.0,7334.0,3022.0,3176.0,2807.0,2968.0,3219.0,3273.0,3252.0
171,ARE,United Arab Emirates,NaN,NaN,NaN,433.0,381.0,407.0,464.0,519.0,...,159.0,209.0,279.0,538.0,677.0,631.0,603.0,417.0,663.0,888.0
172,GBR,United Kingdom,43632.0,43371.0,64726.0,80230.0,85160.0,90909.0,98577.0,107933.0,...,299718.0,292097.0,269363.0,238150.0,193510.0,149799.0,126055.0,117234.0,123067.0,118913.0
173,TZA,Tanzania,265184.0,288103.0,292148.0,564520.0,883250.0,829671.0,498732.0,570367.0,...,435630.0,321909.0,118731.0,109286.0,131243.0,101021.0,102099.0,88492.0,211845.0,281498.0
174,USA,United States,464887.0,513882.0,579952.0,623069.0,631051.0,623294.0,607024.0,563837.0,...,281219.0,279548.0,275461.0,264574.0,264763.0,262023.0,263662.0,267222.0,273202.0,272898.0
175,URY,Uruguay,87.0,81.0,90.0,138.0,113.0,132.0,138.0,133.0,...,140.0,145.0,168.0,189.0,174.0,181.0,203.0,272.0,301.0,274.0
176,UZB,Uzbekistan,NaN,NaN,NaN,8000.0,8001.0,2627.0,2900.0,3159.0,...,1054.0,821.0,555.0,311.0,214.0,176.0,141.0,125.0,107.0,26.0
177,VUT,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,3.0,4.0,4.0,NaN,2.0,2.0,NaN,NaN,NaN
178,VEN,"Venezuela, RB",1750.0,1720.0,1990.0,2221.0,2177.0,1613.0,1596.0,301.0,...,200907.0,201161.0,201313.0,201547.0,202022.0,203644.0,204340.0,173600.0,173754.0,172017.0
179,VNM,Vietnam,21150.0,20148.0,16263.0,5084.0,5000.0,34400.0,34400.0,15000.0,...,2357.0,2357.0,2357.0,1928.0,990.0,NaN,NaN,NaN,NaN,NaN
180,YEM,"Yemen, Rep.",2938.0,29977.0,59680.0,54450.0,48306.0,53453.0,53546.0,40964.0,...,117363.0,140169.0,170854.0,190092.0,214740.0,237182.0,241288.0,257645.0,267173.0,269763.0
181,ZMB,Zambia,138049.0,140676.0,142104.0,141126.0,141126.0,129965.0,131139.0,165072.0,...,112931.0,83485.0,56785.0,47857.0,45632.0,25653.0,23594.0,25578.0,26447.0,29338.0
182,ZWE,Zimbabwe,190950.0,197627.0,237713.0,100482.0,2199.0,514.0,595.0,806.0,...,3981.0,3468.0,3995.0,4435.0,4561.0,4356.0,6389.0,6079.0,6950.0,7418.0

### 1990

In [17]:
# create the sub-frame
temp = pd.DataFrame(columns=['Country Code','Country Name','1990']) 
temp['Country Code'] = refugees['Country Code']
temp['Country Name'] = refugees['Country Name']
temp['1990'] = refugees['1990']
# remove NaN values
temp = temp.dropna().sort_values('1990',ascending=False)
# save the sub-frame 
#temp.to_pickle('../data/ref_by_c_asylum/1990_asy_pickle')
ref90 = pd.read_pickle('../data/ref_by_c_asylum/1990_asy_pickle')
ref90.head(20)

    Country Code          Country Name       1990
77           IRN    Iran, Islamic Rep.  4174401.0
124          PAK              Pakistan  3255975.0
152          SDN                 Sudan  1031050.0
84           JOR                Jordan   929737.0
99           MWI                Malawi   926725.0
122          PSE    West Bank and Gaza   910637.0
63           DEU               Germany   816000.0
56           ETH              Ethiopia   773764.0
174          USA         United States   464887.0
148          SOM               Somalia   460000.0
47           COD      Congo, Dem. Rep.   416435.0
105          MEX                Mexico   356400.0
68           GIN                Guinea   325000.0
91           LBN               Lebanon   304599.0
35           CHN                 China   287276.0
157          SYR  Syrian Arab Republic   284856.0
41           CRI            Costa Rica   276210.0
42           CIV         Cote d'Ivoire   272281.0
26           BDI               Burundi   268403.0
173          TZA              Tanzania   265184.0

### Choropleth

In [18]:
data = [ dict(
        type = 'choropleth',
    
    # can take country codes 
        locations = ref90['Country Code'],
        z = ref90['1990'],
        text = ref90['Country Name'],
        colorscale = [[0,"rgb(0, 89, 179)"],[0.8, "rgb(26, 140, 255)"],[1,"rgb(255, 255, 255)"]],
        autocolorscale = False,
        reversescale = True,
        marker = dict(
            line = dict (
                color = 'rgb(180,180,180)',
                width = 0.5
            ) ),
        colorbar = dict(
            autotick = False,
            title = 'Refugee Population<br>by Country of Asylum'),
      ) ]

In [19]:
layout = dict(
    title = '1990 Refugee Population by Country of Asylum<br>Source:\
            <a href="https://data.worldbank.org/indicator/SM.POP.REFG">\
            The World Bank</a>',
    geo = dict(
        showframe = False,
        showcoastlines = False,
        projection = dict(
            type = 'Mercator'
        )
    )
)

In [20]:
fig = dict( data=data, layout=layout )
py.iplot( fig, validate=False, filename='d3-world-map_1990_asy' )

### 2016

In [21]:
# create the sub-frame
temp = pd.DataFrame(columns=['Country Code','Country Name','2016']) 
temp['Country Code'] = refugees['Country Code']
temp['Country Name'] = refugees['Country Name']
temp['2016'] = refugees['2016']
# remove NaN values
temp = temp.dropna().sort_values('2016',ascending=False)
# save the sub-frame 
#temp.to_pickle('../data/ref_by_c_asylum/2016_asy_pickle')
ref16 = pd.read_pickle('../data/ref_by_c_asylum/2016_asy_pickle')
ref16.head(20)

    Country Code          Country Name       2016
166          TUR                Turkey  2869379.0
84           JOR                Jordan  2860669.0
122          PSE    West Bank and Gaza  2158274.0
91           LBN               Lebanon  1476618.0
124          PAK              Pakistan  1352551.0
77           IRN    Iran, Islamic Rep.   979435.0
169          UGA                Uganda   940815.0
56           ETH              Ethiopia   791616.0
63           DEU               Germany   669408.0
157          SYR  Syrian Arab Republic   562811.0
47           COD      Congo, Dem. Rep.   451947.0
86           KEN                 Kenya   451077.0
152          SDN                 Sudan   421454.0
33           TCD                  Chad   391235.0
28           CMR              Cameroon   375393.0
35           CHN                 China   317239.0
59           FRA                France   304507.0
173          TZA              Tanzania   281498.0
13           BGD            Bangladesh   276198.0
174          USA         United States   272898.0

### Choropleth

In [22]:
data = [ dict(
        type = 'choropleth',
    
    # can take country codes 
        locations = ref16['Country Code'],
        z = ref16['2016'],
        text = ref16['Country Name'],
        colorscale = [[0,"rgb(0, 89, 179)"],[0.8, "rgb(26, 140, 255)"],[1,"rgb(255, 255, 255)"]],
        autocolorscale = False,
        reversescale = True,
        marker = dict(
            line = dict (
                color = 'rgb(180,180,180)',
                width = 0.5
            ) ),
        colorbar = dict(
            autotick = False,
            title = 'Refugee Population<br>by Country of Asylum'),
      ) ]

In [23]:
layout = dict(
    title = '2016 Refugee Population by Country of Asylum<br>Source:\
            <a href="https://data.worldbank.org/indicator/SM.POP.REFG">\
            The World Bank</a>',
    geo = dict(
        showframe = False,
        showcoastlines = False,
        projection = dict(
            type = 'Mercator'
        )
    )
)

In [24]:
fig = dict( data=data, layout=layout )
py.iplot( fig, validate=False, filename='d3-world-map_2016_asy' )

### Slider Animations with Choropleths

In [4]:
refugees=pd.read_pickle("../data/ref_by_c_asylum/refugee_asy_pickle")
refugees.head(20)

,Country Code,Country Name,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,AFG,Afghanistan,50.0,38.0,60025.0,32132.0,19131.0,19605.0,18775.0,5.0,...,42.0,37.0,37.0,6434.0,3009.0,16187.0,16863.0,300423.0,257554.0,59770.0
1,ALB,Albania,NaN,NaN,3000.0,3000.0,3000.0,4720.0,4925.0,30.0,...,77.0,65.0,70.0,76.0,82.0,86.0,93.0,104.0,104.0,111.0
2,DZA,Algeria,169110.0,169124.0,219314.0,219067.0,219073.0,192489.0,190267.0,170746.0,...,94137.0,94093.0,94137.0,94144.0,94148.0,94133.0,94150.0,94128.0,94182.0,94220.0
3,AGO,Angola,11557.0,11022.0,11002.0,10878.0,10686.0,10884.0,9381.0,9364.0,...,12069.0,12710.0,14734.0,15155.0,16223.0,23413.0,23783.0,15474.0,15555.0,15537.0
4,ATG,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN
5,ARG,Argentina,11735.0,11529.0,11515.0,11636.0,11901.0,10314.0,10430.0,10522.0,...,3263.0,2845.0,3230.0,3276.0,3361.0,3488.0,3362.0,3498.0,3207.0,3222.0
6,ARM,Armenia,NaN,NaN,300000.0,334000.0,304039.0,218950.0,218950.0,219000.0,...,4566.0,3953.0,3607.0,3296.0,2918.0,2854.0,13732.0,17640.0,19319.0,17873.0
7,ABW,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN
8,AUS,Australia,97915.0,53117.0,52604.0,53505.0,57575.0,62145.0,67313.0,66074.0,...,22164.0,20919.0,22548.0,21805.0,23434.0,30083.0,34503.0,35582.0,36917.0,42107.0
9,AUT,Austria,34938.0,34508.0,62355.0,57687.0,40703.0,34385.0,89116.0,84394.0,...,30773.0,37557.0,38906.0,42630.0,47073.0,51730.0,55598.0,60747.0,72216.0,93182.0
10,AZE,Azerbaijan,NaN,NaN,246000.0,228840.0,231635.0,233682.0,233692.0,233715.0,...,2352.0,2061.0,1642.0,1891.0,1730.0,1468.0,1380.0,1299.0,1278.0,1183.0
11,BHS,"Bahamas, The",NaN,NaN,374.0,59.0,NaN,8.0,48.0,60.0,...,NaN,NaN,NaN,28.0,28.0,37.0,15.0,13.0,8.0,9.0
12,BHR,Bahrain,1780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,48.0,139.0,165.0,199.0,289.0,294.0,311.0,247.0,270.0
13,BGD,Bangladesh,145.0,40260.0,245154.0,198954.0,116228.0,51118.0,30692.0,21603.0,...,27573.0,28389.0,228586.0,229253.0,229669.0,230697.0,231145.0,232472.0,231958.0,276198.0
14,BRB,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
15,BLR,Belarus,NaN,NaN,NaN,NaN,1822.0,28988.0,30525.0,50.0,...,649.0,609.0,580.0,589.0,595.0,576.0,604.0,925.0,1809.0,1632.0
16,BEL,Belgium,25911.0,24071.0,24292.0,24908.0,19497.0,31691.0,36060.0,36060.0,...,17575.0,17026.0,15545.0,17892.0,22402.0,22024.0,25629.0,29179.0,35314.0,42128.0
17,BLZ,Belize,30657.0,29969.0,20351.0,8912.0,8857.0,8750.0,8534.0,8387.0,...,358.0,277.0,230.0,134.0,78.0,28.0,21.0,10.0,35.0,NaN
18,BEN,Benin,456.0,456.0,293.0,156241.0,70406.0,23843.0,5960.0,2918.0,...,7621.0,6933.0,7205.0,7139.0,7217.0,4966.0,194.0,415.0,530.0,799.0
19,BOL,Bolivia,200.0,341.0,491.0,669.0,734.0,681.0,698.0,333.0,...,632.0,664.0,679.0,695.0,716.0,733.0,748.0,763.0,775.0,761.0

### Melt year columns into a row

In [9]:
df = pd.melt(refugees, id_vars=["Country Name", "Country Code"], 
                  var_name="Year", value_name="Refugees")
# df.to_pickle('../data/ref_by_c_asylum/melt_pickle')
refugees=pd.read_pickle('../data/ref_by_c_asylum/melt_pickle')
refugees.head(20)

           Country Name Country Code  Year  Refugees
0           Afghanistan          AFG  1990      50.0
1               Albania          ALB  1990       NaN
2               Algeria          DZA  1990  169110.0
3                Angola          AGO  1990   11557.0
4   Antigua and Barbuda          ATG  1990       NaN
5             Argentina          ARG  1990   11735.0
6               Armenia          ARM  1990       NaN
7                 Aruba          ABW  1990       NaN
8             Australia          AUS  1990   97915.0
9               Austria          AUT  1990   34938.0
10           Azerbaijan          AZE  1990       NaN
11         Bahamas, The          BHS  1990       NaN
12              Bahrain          BHR  1990    1780.0
13           Bangladesh          BGD  1990     145.0
14             Barbados          BRB  1990       NaN
15              Belarus          BLR  1990       NaN
16              Belgium          BEL  1990   25911.0
17               Belize          BLZ  1990   30657.0
18                Benin          BEN  1990     456.0
19              Bolivia          BOL  1990     200.0

In [11]:
data = [dict(type='choropleth',
            locations = refugees['Country Code'],
            z=refugees['Refugees'],
            text = refugees['Country Name'],
            colorscale = [[0,"rgb(0, 89, 179)"],[0.8, "rgb(26, 140, 255)"],[1,"rgb(255, 255, 255)"]],
            autocolorscale = False,
            reversescale = True,
            marker = dict(
                 line = dict (
                    color = 'rgb(180,180,180)',
                    width = 0.5
                ) 
             ),
            colorbar = dict(
            autotick = False,
            title = 'Refugee Population<br>by Country of Asylum')
            )]

In [12]:
for i in range(26):
    data.append(data[0].copy())
    data[-1]['z'] = data[0]['z'] * np.random.rand(*data[0]['z'].shape)

In [13]:
steps = []
for i in range(len(data)):
    step = dict(method='restyle',
                args=['visible', [False] * len(data)],
                label='{}'.format(i + 1990))
    step['args'][1][i] = True
    steps.append(step)

In [14]:
sliders = [dict(active=0,
                pad={"t": 1},
                steps=steps)]

In [15]:
layout = dict(
    title = 'Refugee Population by Country of Asylum 1990-2016<br>Source:\
            <a href="https://data.worldbank.org/indicator/SM.POP.REFG">\
            The World Bank</a>',
    geo = dict(
        showframe = False,
        showcoastlines = False,
        projection = dict(type = 'Mercator')
    ),
    sliders=sliders)

In [16]:
fig = dict(data=data, 
           layout=layout)

In [17]:
py.iplot(fig, validate=False, filename='d3-world-map_asylum_sliders')